GET  https://localhost:5001/api/people/6e6b9dc3-91b3-43b1-a87b-d5efab53986f
Accept: text/plain
Content-Type: application/json

###

GET  https://localhost:8888/api/people
Accept: text/plain
Content-Type: application/json

###

POST https://localhost:5001/api/people
Accept: text/plain
Content-Type: application/json

{
    "firstName": "Anderson",
    "lastName": "Ritter de Souza",
    "cpf": "01957019093"
}

###

DELETE  https://localhost:5001/api/People/6e6b9dc3-91b3-43b1-a87b-d5efab53986f
Accept: text/plain
Content-Type: application/json

###

PATCH https://localhost:8888/api/People/6e6b9dc3-91b3-43b1-a87b-d5efab53986f
Accept: text/plain
Content-Type: application/json

{
    "firstName": "Anderson",
    "lastName": "Ritter de Souzas",
    "cpf": "01957019093"
}
